### ISSUE TITLE
Nexus: Failed LoadLibrary on "reffect.dll". Incompatible.

### ISSUE THREAD

**Issue by sqrt-7** [Zerthox/gw2-reffect#50]
Hi,

I have the latest reffect.dll and Nexus is up to date, but I'm unable to get reffect to work since the GW2 patch a couple of weeks ago.

`Failed LoadLibrary on "reffect.dll". Incompatible. Last Error: 126`

![Screenshot From 2024-10-31 10-25-06](https://github.com/user-attachments/assets/1b61f19b-9555-4a35-b7e5-1db6440486fb)

**Comment by Zerthox** [comment]
This is unrelated to any GW2 patches, your operating system failed to load the addon with the error "module not found". Some things you can try:
- Redownload the addon in case the file somehow got corrupted
- Reinstall Visual C++ Redistributable in case you somehow "lost" some of the required libraries
- Run a Windows system file repair to fix missing or corrupted system files

If you need more technical support, it's probably quicker and easier to ask in the Raidcore (Nexus) Discord.
